### ISSUE TITLE
Join the big image sprint at SciPy Japan 2020

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#163]
dask-image will join a "big image" sprint at SciPy Japan next week.  There's more detail about the sprint topics here: https://hackmd.io/qpiRFdIsTdCAfdr_C2mMUA

The sprint will be held remotely on November 1-2, 9am-5pm Tokyo time. Anyone who wants to participate is welcome to join. We welcome asynchronous participation too, if the time difference is not a friendly one for you.

Let me know if you want to be involved!

**Comment by m-albert** [comment]
@GenevieveBuckley I'd be super happy to participate :)

Unfortunately the schedule translates to 1am-9am in Zurich. I could join at the beginning and / or towards the end. Or asynchronously!

**Comment by jni** [comment]
@m-albert async works! 😊 Also @snowformatics might be joining from Europe, probably working on jni.github.io/skan, in case you have some interest in skeletons. =) See jni/skan#96

**Comment by GenevieveBuckley** [comment]
Asynchronous is great! It'd be great to have you around @m-albert 😄

**Comment by GenevieveBuckley** [comment]
Here's a copy of the list of possible sprint ideas from the hackmd page:
- [ ] FEATURE: add deconvolution implementation
     * https://github.com/dask/dask-blog/pull/77
     * https://github.com/dask/dask-image/issues/149
- [ ] FEATURE: pathlib input for imread functions
    * https://github.com/dask/dask-image/issues/139
- [ ] MAINTENANCE: rename `sum` to `sum_labels` and add a deprecation warning
    * https://github.com/dask/dask-image/issues/123
- [ ] TUTORIALS: Turn example pipeline from Genevieve's 2020 talks into a PR for the dask-examples repository.
    * https://github.com/GenevieveBuckley/dask-image-talk-2020
    * https://github.com/dask/dask-examples
- [ ] TUTORIALS: Clarify dask best practices in napari tutorials.
    - [ ] Update [applications/dask.md](https://github.com/napari/tutorials/blob/master/applications/dask.md) to add a similar note like this https://github.com/dask/dask-blog/pull/76
    - [ ] Simplify dask in example #1: https://github.com/napari/napari/pull/1610
    - [ ] Simplify dask in example #2: https://github.com/napari/tutorials/pull/64
    - [ ] Update dask array creation example using map_blocks as best practices ([see comment](https://github.com/dask/dask/issues/5913#issuecomment-714536079)): https://docs.dask.org/en/latest/array-creation.html#using-dask-delayed
    - [ ] Update dask array stack/concatenate/block guide to talk about map_blocks best practices ([see comment](https://github.com/dask/dask/issues/5913#issuecomment-714536079)): https://docs.dask.org/en/latest/array-stack.html
- [ ] DOCUMENTATION: Add a page to the docs with links to youtube talks and slides from previous presentations.
    * https://github.com/GenevieveBuckley/dask-image-talk-2020
    * https://github.com/jakirkham/scipy2019
- [ ] DOCUMENTATION: Document how to create testing environments locally
- [ ] TESTS: Add cron job with github actions to schedule test runs monthly/fortnightly. 
    * Here's an example of someone adding a cron job with github actions to another repository: https://github.com/koaning/scikit-lego/pull/378
- [ ] TESTS: Make a test environment with unpinned dependencies (or --pre dependencies), so we have an early warning if new releases will break our code.
- [ ] TESTS: Run the test suite as part of our github actions PyPI release process
     * https://github.com/dask/dask-image/issues/147
- [ ] PLUGIN: Make a napari plugin that can handle bioformats image data (use pims, model on dask-image imread)
- [ ] MAINTENANCE: code style improvements suggested by @jni (move code out of __init__.py, use standard import abbreviations, etc)
    * https://github.com/dask/dask-image/issues/101
- [ ] PERFORMANCE: Profile code with `da.stack`, `da.concatenate`, and `da.map_blocks` to see if we can get speed improvements.
    * Some initial work has been done here, but still lots more to do! https://github.com/dask/dask-image/issues/161

**Comment by m-albert** [comment]
@GenevieveBuckley Cool that you wrote up sprint ideas :)

I might have a look at the deconvolution and what has been discussed about it so far. I've been using `dask` and `cupy` together with multi-view image deconvolution here https://github.com/m-albert/MVRegFus and it'd be nice to play around some more!

@jni I actually do have an interest in skeletons! Will have a look at your package `skan` :)
@snowformatics if you're up for a chat (we're in the same time zone!) you could pm me on [twitter](https://twitter.com/_malberto) or write here :)

**Comment by tkoyama010** [comment]
I will do.
> DOCUMENTATION: Add a page to the docs with links to youtube talks and slides from previous presentations.
> https://github.com/GenevieveBuckley/dask-image-talk-2020
> https://github.com/jakirkham/scipy2019

**Comment by GenevieveBuckley** [comment]
> I might have a look at the deconvolution and what has been discussed about it so far. I've been using `dask` and `cupy` together with multi-view image deconvolution here https://github.com/m-albert/MVRegFus and it'd be nice to play around some more!

Yes, I think we have a lot of similar interests!

**Comment by tkoyama010** [comment]
Next. I will do.
>  MAINTENANCE: rename sum to sum_labels and add a deprecation warning
#123

**Comment by tkoyama010** [comment]
Sorry It does not make sense to me. I could understand that we should rename function. But how can we add deprecation warning?
>MAINTENANCE: rename sum to sum_labels and add a deprecation warning
>#123

**Comment by GenevieveBuckley** [comment]
Hi @tkoyama010, we can use the python [warnings](https://docs.python.org/3/library/warnings.html) library for that.


* Add a new function named `sum_labels` that is a copy of what `sum` does now
* Keep the old function named `sum`, but change it so that:
    * It gives a DeprecationWarning message ([see here](https://docs.python.org/3/library/warnings.html)), telling people to use the `sum_labels` function instead
    * It then returns the `sum_labels` function

**Comment by tkoyama010** [comment]
Thanks @GenevieveBuckley . I got it.

**Comment by tkoyama010** [comment]
Next I will do.
> FEATURE: pathlib input for imread functions #139

**Comment by tkoyama010** [comment]
Next I will do.

> Running test suite as part of PyPI release #147

I think I will update the release_guide.rst .

**Comment by GenevieveBuckley** [comment]
> 
> 
> Next I will do.
> 
> > Running test suite as part of PyPI release #147
> 
> I think I will update the release_guide.rst .

I think what this means is that we should include the tests as part of the release github action, rather than adding a note to the release guide. Does that make sense?

**Comment by tkoyama010** [comment]
@GenevieveBuckley  Yes. Thanks.

**Comment by tkoyama010** [comment]
Next. I will do 
> MAINTENANCE: code style improvements suggested by @jni (move code out of init.py, use standard import abbreviations, etc)
#101

**Comment by tkoyama010** [comment]
Thanks to the maintainers of the dask project, you make the sprint for Scipy Japan 2020 :jp: excellent. I look forward to seeing you at another Python Conference again.

**Comment by GenevieveBuckley** [comment]
Thanks to everyone who participated! So many excellent contributions
