### ISSUE TITLE
Add new maintainer checklist to the docs

### ISSUE THREAD

**Issue by GenevieveBuckley** [dask/dask-image#195]
It's probably a good idea if we add this info to our docs. Things that happen infrequently and have multiple steps are always a bit too easy to forget parts of.

Checklist for adding a new maintainer:
- [ ] Share email addresses with the current maintainer team
- [ ] Add them to the dask-image repo: https://github.com/dask/dask-image/settings/access
- [ ] Make a new PR in the github.com/conda-forge/dask-image-feedstock/ repo
   - [ ] Add their name to the README at the dask-conda-feedstock repo
   - [ ] Add their name to  dask-image-feedstock/recipe/meta.yaml 
   ...when the PR is merged the bot will add anyone in the recipe list to the team maintaining this feedstock automatically

**Comment by m-albert** [comment]
- [ ] Add their PyPI user as maintainer to the dask-image pypi project https://pypi.org/project/dask-image
